### ISSUE TITLE
Write a README.md

### ISSUE THREAD

**Issue by rowhitswami** [rowhitswami/whatsapp-loop#1]
This issue is to encourage those who are contributing to an amazing open-source community of Github for the first time.
This project is meant to send messages in loop in [WhatsApp](https://web.whatsapp.com/).
First you need to have web version of WhatsApp in your Google Chrome (only supported browser).
After login, choose your contact and open Dev Tools in Chrome and paste the code of **main.js** in the console and hit enter. Please understand code and write every aspect about it.

Do write the README.md explaining each section briefly.

**Comment by kritisingh1** [comment]
I'll take this up!

**Comment by rowhitswami** [comment]
@kritisingh1 Yes go ahead!
